#!/bin/bash

apt-get install python-pip -y
apt-get install python-dev build-essential libcanberra-gtk3-module  -y
apt-get install sqlite3

wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py

pip install pycrypto
pip install paramiko


