#!/bin/bash

apt-get install python-pip  python-dev build-essential libcanberra-gtk3-module sqlite3 python-pygame -y

wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py

pip install pycrypto
pip install paramiko
